version: "3.9"

services:
    jupyter:
        image: data_science_analysis
        build: .
        restart: always
        volumes:
            - ./src:/home/jovyan/notebooks
        ports:
            - "8889:8889"
