version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    
    restart: always      

    #command: npm run start:dev
    command: npm run start
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    volumes:
      - ./:/usr/src/app
      - web_node_modules:/usr/src/app/node_modules:rw
    ports:
      - "3000:3000"

volumes:
  web_node_modules:

# Evoluir com base nessa referência
# https://blog.logrocket.com/node-js-docker-improve-dx/
