version: '3.7'

services:
  app:
    build: .
    command: sh -c "npm start"
    ports:
      - 4200:4200
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
volumes:
  node_modules:

  #https://markfknight.dev/posts/angular-in-docker/

  #Coloque a informacção abaixo no arquivo package.json do projeto
  #"start": "ng serve --open --host 0.0.0.0 --port 4200 --disable-host-check",
  #para windown só funcionou com esse "start": "export NODE_OPTIONS=--openssl-legacy-provider && ng serve --host 0.0.0.0 --disable-host-check --poll=2000",
  
  #Referencias para criaçao de componentes angular
  #https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/sorting
  
