version: '3.7'

services:
  app:
    build: .
    command: sh -c "npm start"
    ports:
      - 4200:4200
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
volumes:
  node_modules:

  #https://markfknight.dev/posts/angular-in-docker/

  #Coloque a informacção abaixo no arquivo package.json do projeto
  #"start": "ng serve --open --host 0.0.0.0 --port 4200 --disable-host-check",